PruebaAlternativaProyecto/src/main/java/Controlador/LibroBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controlador;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javassist.bytecode.analysis.Analyzer;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import modelo.dao.AutorDao;
import modelo.entidad.Autor;
import modelo.entidad.Libro;

/**
 *
 * @author ADMIN
 */
@ManagedBean(name ="bkn_Lll")
@RequestScoped
public class LibroBean {

    /**
     * Creates a new instance of LaboratorioDesaUI
     */ 
   
    private List<Autor> lista;
    private List<Integer>ListaAnios;
  
    Libro libro;
    
    @PostConstruct
   public void init(){
     ListaAnios= new ArrayList();
     libro = new Libro();
     
     lista= new ArrayList();
      LlenarListaAnios();
     
   }

    public List<Integer> getListaAnios() {
        return ListaAnios;
    }

    public void setListaAnios(List<Integer> ListaAnios) {
        this.ListaAnios = ListaAnios;
    }

    public Libro getLibro() {
        return libro;
    }

    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    public List<Autor> getLista() {
        return lista;
    }

    public void setLista(List<Autor> lista) {
        this.lista = lista;
    }

  
   public void mostrar(){
       for(Autor i: lista){
           System.out.println(i.getAutor());
       
       System.out.println(libro.getTitulo());
   }
   }
 
   public Integer obtenerFechaActual(){

        Calendar fecha = new GregorianCalendar();
                                                      
        int anio = fecha.get(Calendar.YEAR);
        System.out.println(anio);
        return anio;
       
   }
   public void LlenarListaAnios(){
       int anioInicio = 1960;
       for(Integer i: ListaAnios){
           if(anioInicio<=obtenerFechaActual()){
               System.out.println(i);
               ListaAnios.add(anioInicio);
             anioInicio = anioInicio + 1;   
           }
          
       }
   }
   public void detalle(){
       System.out.println(libro.getTitulo());
   }
   public void clear(){
   libro.setTitulo(null);
   libro.setPortada(null);
   
   }
   

}
   
  

PruebaAlternativaProyecto/src/main/webapp/pages/AddAutor.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Nuevo Autor</h2>
       
    <h:form id="form-agregar">
           
           <p:panel id="panl" header="Agregar Autor">
         <h:panelGrid id="DatoPersonales" columns="3" cellpadding="5">
            
              <h:outputLabel for="txtAutor" value="Autor:" style="font-weight:bold"/>
              <h:inputText id="txtAutor" value="#{bkn_autor.autor.autor}" required="true" label="autor" requiredMessage="Ingrese su Nombre" validatorMessage="Tu nombre solo puede tener alfabetos">
             <f:validateRegex for="txtAutor" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1.]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1.]+$"/>
            </h:inputText>
            <p:message for="txtAutor" />
           
 
        </h:panelGrid>
               <p:commandButton value="Agregar" ajax="false"  action="#{bkn_autor.autorAgregar()}"/> 
               <p:commandButton value="Actualizar" ajax="false"  action="#{bkn_autor.actualizarCantidad()}"/> 
     
    </p:panel>
     </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/AddCategoria.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Nueva Categoria</h2>
       
    <h:form id="form-agregar">
        <p:messages id="mensajes" severity="info,fatal" autoUpdate="false"/>   
           <p:panel id="panl" header="Agregar Categoria">
         <h:panelGrid id="DatoPersonales" columns="3" cellpadding="5">
            
              <h:outputLabel for="txtCategoria" value="Categoria:" style="font-weight:bold"/>
              <h:inputText id="txtCategoria" value="#{bkn_categoria.categoria.categoria}" required="true" label="categoria" requiredMessage="Ingrese categoria" validatorMessage="Categoria solo puede tener alfabetos">
             <f:validateRegex for="txtCategoria" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$"/>
            </h:inputText>
            <p:message for="txtCategoria" />
           
 
        </h:panelGrid>
               <p:commandButton value="Agregar" ajax="false" actionListener="#{bkn_categoria.categoriaAgregar()}"/>  
     
    </p:panel>
     </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/AddLibro.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Nuevo Libro</h2>
       <h:form id="form-agregar" enctype="multipart/form-data">
         
          
           <p:panel id="panl" header="Agregar">
         <p:panelGrid id="DatoLibro" columns="2">    
        
         <p:panelGrid id="ImagenDato" columns="3">
            
            
              <h:outputLabel for="txtTitulo" value="Titulo:" style="font-weight:bold"/>
              <h:inputText id="txtTitulo" value="#{bkn_Libro.libro.titulo}" required="true" label="Titulo" requiredMessage="Ingrese Titulo" validatorMessage="El titulo solo puede tener alfabetos">
             <f:validateRegex for="txtTitulo" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$"/>
            </h:inputText>
            <p:message for="txtTitulo" />
            
             <p:outputLabel  value="Fecha de Edición:"/>
             <p:selectOneMenu value="#{bkn_Libro.libro.anioEdicion}" style="font-weight:bold;">
                   <f:selectItems value="#{bkn_Libro.listaAnios}"/> 
              </p:selectOneMenu>
            <br/>
            
            
             <h:outputLabel for="txtCantidad" value="Cantidad" style="font-weight:bold"/>
             <h:inputText id="txtCantidad" value="#{bkn_Libro.libro.cantidd}" required="true" label="cantidad" requiredMessage="Ingrese Cantidad" validatorMessage="Solo numeros">
             <f:converter converterId="javax.faces.Integer" />
            </h:inputText>
            <p:message for="txtCantidad" />
            
              <p:outputLabel  value="Autor:"/>
              <p:selectOneMenu value="#{bkn_Libro.libro.autor.idAutor}" style="font-weight:bold;">
                  <f:selectItems value="#{bkn_Libro.listaAutores}"  var="a" itemLabel="#{a.autor}" itemValue="#{a.idAutor}"/> 
              </p:selectOneMenu>
            <br/> 
            
              <p:outputLabel  value="Categoria:"/>
              <p:selectOneMenu value="#{bkn_Libro.libro.categoria.idCategoria}" style="font-weight:bold;">
                  <f:selectItems value="#{bkn_Libro.listaCategorias}"  var="c" itemLabel="#{c.categoria}" itemValue="#{c.idCategoria}"/> 
              </p:selectOneMenu>
            <br/>
             
             
             
              
            
        </p:panelGrid>
        <p:graphicImage id="grapImage" value="/Temporal/#{bkn_Libro.imagenLibroTemporal}" width="450" height="350" />     
        <br/>
          <p:fileUpload value="#{bkn_Libro.file}" mode="simple" allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
                        sizeLimit="512000"/>
        </p:panelGrid> 
               
         <p:commandButton value="Agregar" ajax="false" update="grapImage" actionListener="#{bkn_Libro.upload()}" styleClass="p-mt-3 ui-button-outlined p-d-block"/> 
         
    </p:panel>
         
            
     </h:form> 
   
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/AddPrestamo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Realizar Prestamo</h2>
       
    <h:form id="form-agregar">
           
           <p:panel id="panl" header="Agregar Prestamo">
         <h:panelGrid id="DatoDePrestamo" columns="3" cellpadding="5">
          
              <p:outputLabel  value="Usuario:"/>
              <p:selectOneMenu value="#{PrestamoBean.prestamo.usuario.idUsuario}" style="font-weight:bold;">
                  <f:selectItems value="#{PrestamoBean.listaUsuarios}"  var="u" itemLabel="#{PrestamoBean.NombreYApellido(u)}" itemValue="#{u.idUsuario}"/> 
              </p:selectOneMenu>
            <br/> 
             <p:outputLabel  value="Libro:"/>
             <p:selectOneMenu value="#{PrestamoBean.prestamo.libro.idLibro}" style="font-weight:bold;">
                 <f:selectItems value="#{PrestamoBean.listaLibros}"  var="lib" itemLabel="#{lib.titulo}" itemValue="#{lib.idLibro}"/> 
              </p:selectOneMenu>
            <br/> 
            
            <p:outputLabel  value="Empleado:"/>
            <p:selectOneMenu value="#{PrestamoBean.prestamo.empleado.idEmpleado}" style="font-weight:bold;">
                <f:selectItems value="#{PrestamoBean.listaEmpleados}"  var="e" itemLabel="#{PrestamoBean.NombreYApellidoEm(e)}" itemValue="#{e.idEmpleado}"/> 
              </p:selectOneMenu>
            <br/> 
            <p:outputLabel  value="Fecha:"/>
            <p:calendar value="#{PrestamoBean.prestamo.fechaSalida}"/>
             <br/> 
                 <p:outputLabel  value="Estado:"/>
                 <p:selectOneMenu value="#{PrestamoBean.prestamo.estado}" style="font-weight:bold;">
                     <f:selectItem itemLabel="Activo" itemValue="Activo"/>
                    <f:selectItem itemLabel="INACTIVO" itemValue="INACTIVO"/>
              </p:selectOneMenu>
           
 
        </h:panelGrid>
               <p:commandButton value="Agregar" ajax="false" action="#{PrestamoBean.prestamoAgregar()}"/>  
              
    </p:panel>
     </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/AddUsuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Nuevo Usuario</h2>
       
    <h:form id="form-agregar">
           
           <p:panel id="panl" header="Agregar Usu">
         <h:panelGrid id="DatoPersonales" columns="3" cellpadding="5">
            
              <h:outputLabel for="txtNombre" value="Nombre:" style="font-weight:bold"/>
              <h:inputText id="txtNombre" value="#{bkn_Libro2.usuario.nombre}" required="true" label="nombre" requiredMessage="Ingrese nombre" validatorMessage="El nombre solo puede tener alfabetos">
             <f:validateRegex for="txtNombre" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1.]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1.]+$"/>
            </h:inputText>
            <p:message for="txtNombre" />
            
            <h:outputLabel for="txtApellido" value="Apellido:" style="font-weight:bold"/>
            <h:inputText id="txtApellido" value="#{bkn_Libro2.usuario.apellido}" required="true" label="apellido" requiredMessage="Ingrese apellido" validatorMessage="El apellido solo puede tener alfabetos">
             <f:validateRegex for="txtApellido" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1.]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1.]+$"/>
            </h:inputText>
            <p:message for="txtApellido" />
            
            
              
               <h:outputLabel for="txtTelefono" value="Telefono" style="font-weight:bold"/>
               <h:inputText id="txtTelefono" value="#{bkn_Libro2.usuario.telefono}" required="true" label="telefono" requiredMessage="Ingrese Telefono" validatorMessage="Solo numeros">
             <f:converter converterId="javax.faces.Integer" />
            </h:inputText>
            <p:message for="txtTelefono" />
              
              
                 <p:outputLabel  value="Estado:"/>
                 <p:selectOneMenu value="#{bkn_Libro2.usuario.estado}" style="font-weight:bold;">
                     <f:selectItem itemLabel="Activo" itemValue="Activo"/>
                    <f:selectItem itemLabel="Option2" itemValue="INACTIVO"/>
              </p:selectOneMenu>
            <br/>
           
 
        </h:panelGrid>
               <p:commandButton value="Agregar" ajax="false" actionListener="#{bkn_Libro2.usuarioAgregar()}"/>  
     
    </p:panel>
     </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/ProyectoDesa.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
    <ui:define name="contenido">
        este es el caso de uso1
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/TablaAutor.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Autores Registrados</h2>
    
        
        <h:form >
            <p:dataTable id="tablaPuesto" var="a" value="#{bkn_autor.lista}">
                <p:column headerText="Id">
                    <h:outputText value="#{a.idAutor}" />
                  </p:column>
               <p:column headerText="Nombre">
                   <h:outputText value="#{a.autor}" />
                </p:column>

                                       
                </p:dataTable>
            
        </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/TablaCategoria.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Categorias</h2>
    
        
        <h:form >
            <p:dataTable id="tablaCategoria" var="c" value="#{bkn_categoria.listaCategorias}">
                <p:column headerText="Id Categoria">
                    <h:outputText value="#{c.idCategoria}" />
                  </p:column>
               <p:column headerText="Categoria">
                   <h:outputText value="#{c.categoria}" />
                </p:column>

                                       
                </p:dataTable>
            
        </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/TablaEmpleado.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Empleados Registrados</h2>
    
        
        <h:form  id="form-lista">
            <p:dataTable id="tablaEmpleados" var="e" value="#{beanEm.listasEmpleados}">
                <p:column headerText="Id">
                    <h:outputText value="#{e.idEmpleado}" />
                  </p:column>
               <p:column headerText="Nombre">
                   <h:outputText value="#{e.nombre}" />
                </p:column>
                
                <p:column headerText="Apellido">
                    <h:outputText value="#{e.apellido}" />
                </p:column>
                
                <p:column headerText="Dirección">
                    <h:outputText value="#{e.direccion}" />
                </p:column>
                
                <p:column headerText="Teléfono">
                    <h:outputText value="#{e.telefono}" />
                </p:column>
                
                <p:column headerText="Email">
                    <h:outputText value="#{e.email}" />
                </p:column>
                <p:column headerText="Puesto">
                    <h:outputText value="#{e.puesto.idPuesto}" />
                </p:column>
                
                  <p:column headerText="MODIFICAR" style="text-align: center">
                        <p:commandButton icon="ui-icon-pencil" title="Modificar" oncomplete="PF('dialogoModificar').show();" update=":formModificar" actionListener="#{beanEm.obtenerIdSeleccionadoDeTabla(e)}" >
                            <f:setPropertyActionListener target="#{beanEm.empleado}" value="#{e}"/>
                         </p:commandButton>
                    </p:column>


                                       
                </p:dataTable>
            
        </h:form>
        
         <h:form id="formModificar">
                        <p:dialog id="dlgModificar" header="Modificar Empleado" widgetVar="dialogoModificar" resizable="false" showEffect="fade" hideEffect="explode" modal="true">
                            <p:panelGrid columns="2" style="margin: 0 auto;">                                
                                <p:outputLabel value="Nombre:"/>
                                <p:inputText value="#{beanEm.empleado.nombre}"/>
                                <p:outputLabel value="Apellido:"/>
                                <p:inputText value="#{beanEm.empleado.apellido}"/>
                                 <p:outputLabel value="Direccion:"/>
                                 <p:inputText value="#{beanEm.empleado.direccion}"/>
                                <p:outputLabel value="Telefono:"/>
                                <p:inputText value="#{beanEm.empleado.telefono}"/>
                                <p:outputLabel value="Email:"/>
                                <p:inputText value="#{beanEm.empleado.email}"/>
                               
                                
                                <p:outputLabel  value="Puesto:"/>
                                <p:selectOneMenu value="#{beanEm.empleado.puesto.idPuesto}" style="font-weight:bold;">
                                <f:selectItems value="#{beanEm.listasPuestos}"  var="p" itemLabel="#{p.puesto}" itemValue="#{p.idPuesto}"/> 
                                </p:selectOneMenu>
                                
                            </p:panelGrid>
                            <p:commandButton  value="Guardar" actionListener="#{beanEm.modificarEmpleado()}" update=":form-lista:tablaEmpleados" oncomplete="PF('dialogoModificar').hide();"/>
                            <p:commandButton  value="Cancelar" onclick="PF('dialogoModificar').hide();"/>
                        </p:dialog>
                    </h:form>
       
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/TablaLibros.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Biblioteca</h2>
        
       <h:form id="formListado">
             <p:commandButton value="Refrescar" ajax="false" actionListener="#{bkn_Libro.refrescar()}" styleClass="p-mt-3 ui-button-outlined p-d-block"/> 
           <p:dataTable id="tablaLibros" var="lib" value="#{bkn_Libro.listaLibros}" rows="5" paginator="true">
                <p:column headerText="Id">
                 <h:outputText value="#{lib.idLibro}"/>
                </p:column>
                     <p:column headerText="Titulo">
                         <h:outputText value="#{lib.titulo}" />
                            </p:column>
                            <p:column headerText="Id_Autor">
                                <h:outputText value="#{lib.autor.idAutor}" />
                            </p:column>
                 
                            <p:column headerText="Id_Categoria">
                                <h:outputText value="#{lib.categoria.idCategoria}" />
                            </p:column>
                 
                             <p:column headerText="Anio Edicion">
                                 <h:outputText value="#{lib.anioEdicion}" />
                            </p:column>
                 
                             <p:column headerText="Disponible">
                                 <h:outputText value="#{lib.cantidd}" />
                            </p:column>
                           
                            <p:column>
                                <p:graphicImage value="/Image/#{bkn_Libro.UnioIdMasTitulo(lib)}.jpg"  style="margin-left: 10px;" width="90px" height="90px"/>
                            </p:column>
                
                            <p:column headerText="Visualizar">
                                <p:commandButton value="Ver" icon="ui-icon-zoomin" actionListener="#{bkn_Libro.view(lib)}" ajax="false"/>
                            </p:column>
                           
                          
                   
                </p:dataTable>
           
         </h:form>
        
           
                  
       
                    
                
        
   
    </ui:define>
 </ui:composition>

PruebaAlternativaProyecto/src/main/webapp/pages/TablaPrestamo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      template="/Template/plantilla.xhtml"
          
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"> 
 
    <ui:define name="contenido">
        <h2>Prestamos Realizados</h2>
    
        
        <h:form >
            <p:dataTable id="tablaPrestamos" var="p" value="#{PrestamoBean.listaPrestamos}">
                <p:column headerText="Id">
                    <h:outputText value="#{p.idPrestamo}" />
                  </p:column>
               <p:column headerText="Libro">
                   <h:outputText value="#{p.libro.titulo}" />
                </p:column>
                
                <p:column headerText="Usurio">
                    <h:outputText value="#{p.usuario.nombre}" />
                </p:column>
                
                <p:column headerText="Empleado">
                    <h:outputText value="#{p.empleado.nombre}" />
                </p:column>
                
                <p:column headerText="Fecha">
                    <h:outputText value="#{p.fechaSalida}" />
                </p:column>
                
                <p:column headerText="Estado">
                    <h:outputText value="#{p.estado}" />
                </p:column>
             


                                       
                </p:dataTable>
            
        </h:form>
       
    </ui:define>
 </ui:composition>